### ISSUE TITLE
0509 | Easy | Fibonacci Number

### ISSUE THREAD

**Issue by sankalpdayal5** [sankalpdayal5/LeetCode-Solutions#1]

**Comment by RahulG606** [comment]
I can do this. Could you please assign it to me?

**Comment by sankalpdayal5** [comment]
Also update readme by adding a new row for this question.

**Comment by sankalpdayal5** [comment]
https://leetcode.com/problems/fibonacci-number/

**Comment by sankalpdayal5** [comment]
Assigned @RahulG606
